services:
  dd-agent:
    image: gcr.io/datadoghq/agent:7
    environment:
      - DD_API_KEY=
      - DD_SITE=datadoghq.eu
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=image:gcr.io/datadoghq/agent:*
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: always

  django:
    image: django
    environment:
      - DD_AGENT_HOST=dd-agent
    ports:
      - "8080:8000"
    volumes:
      - ./djangodd:/usr/src/app
    restart: always

